name: BuildAHouse

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: com.zinibu.minecraft.buildahouse.BuildAHouse

commands:
    buildahouse:
        description: Build a house

version: 0.4

